# Train Test Split

## Import the relevant libraries

In [3]:
import numpy as np
from sklearn.model_selection import train_test_split

## Generate some data we are going to split

In [9]:
a= np.arange(1,101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [10]:
b = np.arange(678,9008)
b

array([ 678,  679,  680, ..., 9005, 9006, 9007])

In [11]:
b

array([ 678,  679,  680, ..., 9005, 9006, 9007])

## Split the data

In [16]:
train_test_split(a)

[array([ 94,  73,  63,  14,   4,  25,  67,  79, 100,  42,  88,  34,  27,
         75,  72,  35,  78,  80,  47,  45,  89,  90,  33,   9,  40,  28,
         53,  66,  24,  98,  39,  36,  50,  96,  64,   6,  51,  99,  41,
         69,  23,  46,  32,  71,  57,  38,  31,  74,  21,   3,  60,  93,
         17,  86,   8,   2,  22,   7,  29,  61,  20,  91,  16,  56,   1,
         13,  84,  18,  43,  12,  83,  15,  85,  77,  59]),
 array([87, 82, 49, 30, 54, 37, 10, 58, 52, 68, 55, 26, 97, 48, 65, 95,  5,
        44, 19, 70, 62, 92, 81, 76, 11])]

In [17]:
train_test_split(b)

[array([1381, 7556, 4054, ..., 8112, 4823, 1788]),
 array([8026, 8452, 7106, ..., 5117, 7629, 7450])]

## Explore the result

In [26]:
a_train, a_test = train_test_split(a)

In [30]:
b_train, b_test = train_test_split(b)

In [27]:

a_train.shape, a_test.shape


((75,), (25,))

In [28]:
a_train

array([ 85,  32,  65,  12,  29,  56,  72,  98,  53,  44, 100,  35,  83,
        52,  41,  36,  47,   1,  39,  64,  93,  87,   3,  96,  34,  84,
        49,  82,  51,  19,  21,  63,  40,  26,  57,  90,  67,  14,  54,
        76,  22,  91,  42,  77,  43,  18,  75,  30,  71,  66,  31,  15,
        61,   7,  58,  28,  17,  60,   8,  45,  78,   6,  99,   5,  13,
         4,  86,  24,  74,  79,  70,  81,  69,  50,  16])

In [29]:
a_test


array([48, 27, 37, 20, 80, 23, 11, 55, 62, 10, 68,  2, 92, 25, 46, 95, 73,
       33, 88, 89, 97, 38, 94, 59,  9])

In [32]:

b_train.shape, b_test.shape

((6247,), (2083,))

In [33]:
b_train


array([7335, 2903, 1720, ..., 6067, 2482, 4036])

In [34]:
b_test

array([7947, 5886, 1569, ..., 1108, 5668, 4402])